spring.application.name=msv-reservaciones
server.port=${PORT}

#eureka.client.enabled=false
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver



eureka.instance.instance-id=${spring.application.name}:${random.value}
spring.jpa.show-sql=true


#Creado por mi
spring.jpa.hibernate.ddl-auto=update
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration