server:
  port: 8090 # Puerto estándar para Gateway

spring:
  application:
    name:  api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

  cloud:
    loadbalancer:
      enabled: true

    gateway:
      server:
        webflux:
          routes:
            - id: msv-habitacion
              uri: lb://msv-habitacion
              predicates:
                - Path=/api/habitacion/**
              filters:
                - StripPrefix=2

            - id: msv-huesped
              uri: lb://msv-huesped
              predicates:
                - Path=/api/huesped/**
              filters:
                - StripPrefix=2

            - id: msv-reserva
              uri: lb://msv-reserva
              predicates:
                - Path=/api/reserva/**
              filters:
                - StripPrefix=2

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka