spring.application.name=reserva
server.port=${PORT}

eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


#Creado por mi
spring.jpa.hibernate.ddl-auto=update
spring.autoconfigure.exclude=org.springframework.boot.autoconfig